### ISSUE TITLE
module dependencies attempting to access 'fs' 

### ISSUE THREAD

**Issue by takotaco** [launchdarkly/node-client-sdk#10]
**Describe the bug**
I'm getting this error: 
```
ERROR in ./node_modules/graceful-fs/graceful-fs.js
    Module not found: Error: Can't resolve 'fs' in '/Users/me/dev/myapp/node_modules/graceful-fs'
     @ ./node_modules/graceful-fs/graceful-fs.js 1:9-22
     @ ./node_modules/node-localstorage/node_modules/write-file-atomic/index.js
     @ ./node_modules/node-localstorage/LocalStorage.js
     @ ./node_modules/launchdarkly-node-client-sdk/src/nodePlatform.js
     @ ./node_modules/launchdarkly-node-client-sdk/src/index.js
     @ multi babel-polyfill whatwg-fetch abortcontroller-polyfill blueimp-canvas-to-blob ./app/client.js webpack-hot-middleware/client?name=myapp&timeout=20000&reload=true&quiet=false&noInfo=false

    ERROR in ./node_modules/node-localstorage/LocalStorage.js
    Module not found: Error: Can't resolve 'fs' in '/Users/me/dev/myapp/node_modules/node-localstorage'
     @ ./node_modules/node-localstorage/LocalStorage.js 9:7-20
     @ ./node_modules/launchdarkly-node-client-sdk/src/nodePlatform.js
     @ ./node_modules/launchdarkly-node-client-sdk/src/index.js
     @ multi babel-polyfill whatwg-fetch abortcontroller-polyfill blueimp-canvas-to-blob ./app/client.js webpack-hot-middleware/client?name=myapp&timeout=20000&reload=true&quiet=false&noInfo=false

    ERROR in ./node_modules/winston/lib/winston/common.js
    Module not found: Error: Can't resolve 'fs' in '/Users/me/dev/myapp/node_modules/winston/lib/winston'
     @ ./node_modules/winston/lib/winston/common.js 12:9-22
     @ ./node_modules/winston/lib/winston/container.js
     @ ./node_modules/winston/lib/winston.js
     @ ./node_modules/launchdarkly-node-client-sdk/src/index.js
     @ multi babel-polyfill whatwg-fetch abortcontroller-polyfill blueimp-canvas-to-blob  ./app/client.js webpack-hot-middleware/client?name=myapp&timeout=20000&reload=true&quiet=false&noInfo=false

    ERROR in ./node_modules/winston/lib/winston/transports/file.js
    Module not found: Error: Can't resolve 'fs' in '/Users/me/dev/myapp/node_modules/winston/lib/winston/transports'
     @ ./node_modules/winston/lib/winston/transports/file.js 10:9-22
     @ ./node_modules/winston/lib/winston/transports.js
     @ ./node_modules/winston/lib/winston.js
     @ ./node_modules/launchdarkly-node-client-sdk/src/index.js
     @ multi babel-polyfill whatwg-fetch abortcontroller-polyfill blueimp-canvas-to-blob ./app/client.js webpack-hot-middleware/client?name=myapp&timeout=20000&reload=true&quiet=false&noInfo=false
```

I don't understand why it is trying to access the file system for a client-side web SDK. Help?

**To reproduce**
1. Have an app complied with webpack.
2. `npm install launchdarkly-node-client-sdk@1.4.0 --save`
3. start node server which runs webpack to build bundle.js. webpack fails to compile.

**Expected behavior**
No errors, especially not one related to being able to access fs, as this is a client side sdk.

**Logs**
see above

**SDK version**
   `"launchdarkly-node-client-sdk": "^1.4.0",`

**Language version, developer tools**
node, webpack, react/redux.

**OS/platform**
MacOS

**Additional context**

**Comment by eli-darkly** [comment]
I think this is just a misunderstanding of what "client-side" means in this context. It doesn't mean "in a web browser"— it means "in any context that is not server-side".

A web browser is one _kind_ of client-side environment, but not the only kind. It sounds like you are writing front-end JavaScript code, so what you want to use is [launchdarkly-js-client-sdk](https://github.com/launchdarkly/js-client-sdk).

The purpose of launchdarkly-node-client-sdk is for client-side code that runs _in Node.js_. It differs from the server-side Node SDK, launchdarkly-node-server-sdk, in that it is meant to be deployed in some environment that belongs to an end user, rather than to the application maintainer, and that runs for one end user at a time rather than servicing requests from many users. For instance, it could be a command-line tool. It has nothing to do with web browsers, and if your code is not actually running in Node.js then you have no reason to use this.

**Comment by eli-darkly** [comment]
[Reference guide for the browser JS SDK](https://docs.launchdarkly.com/sdk/client-side/javascript)
[Reference guide for the client-side Node.js SDK](https://docs.launchdarkly.com/sdk/client-side/node-js)
[Reference guide for the server-side Node.js SDK](https://docs.launchdarkly.com/sdk/server-side/node-js)
[Client-side versus server-side SDKs](https://docs.launchdarkly.com/sdk/concepts/client-side-server-side)

**Comment by takotaco** [comment]
Okay, I see. Sorry for the confusion. I'll look into the js SDK you linked, I must have missed that.
